/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import React from "react";

const Header = () => {
  return (
    <Head>
      <title>
        Sistem Pendataan Potensi Nasabah Pada Sektor Perusahaan di Sekitar Bank
        Mandiri KCP Jakarta Ketapang Indah
      </title>
      <meta
        name="description"
        content="Generated by Gusman Wijaya (2200775757) & Harry Sangmahata Purba (2201775533)"
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.png" />
    </Head>
  );
};

export default Header;
